name: Branch Protection

on:
  push:
    branches:
      - main
      - master
      - develop
      - "release/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    # --- FIX HERE ---
    permissions:
      contents: read # Still good to have for general workflow operations
      # Use repository-projects: read for reading branch protection rules
      repository-projects: read # This is the more accurate permission for this API endpoint
    # --- END FIX ---
    steps:
      - name: Check branch protection
        uses: actions/github-script@v6
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              const protection = await github.rest.repos.getBranchProtection({
                owner,
                repo,
                branch
              });

              // Verify required status checks
              if (!protection.data.required_status_checks) {
                throw new Error(`Branch ${branch} must have required status checks`);
              }

              // Verify linear history
              if (!protection.data.required_linear_history) {
                throw new Error(`Branch ${branch} must have linear history enabled`);
              }

              // Verify force push protection (force pushes should be disallowed for protection)
              if (protection.data.allow_force_pushes) {
                throw new Error(`Branch ${branch} must have force push protection enabled (force pushes disallowed)`);
              }

              // Verify deletion protection (deletions should be disallowed for protection)
              if (protection.data.allow_deletions) {
                throw new Error(`Branch ${branch} must have deletion protection enabled (deletions disallowed)`);
              }

              console.log(`Branch ${branch} has all required protection settings.`);

            } catch (error) {
              console.error(`Failed to check branch protection for ${branch}:`, error);
              throw new Error(`Failed to verify branch protection for ${branch}. Please check permissions and branch protection rules. Original error: ${error.message}`);
            }
