name: Branch Protection

on:
  push:
    branches:
      - main
      - master
      - develop
      - "release/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch protection
        uses: actions/github-script@v6
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get branch protection rules
            const protection = await github.rest.repos.getBranchProtection({
              owner,
              repo,
              branch
            });

            // Verify required status checks
            if (!protection.data.required_status_checks) {
              throw new Error(`Branch ${branch} must have required status checks`);
            }

            // Verify linear history
            if (!protection.data.required_linear_history) {
              throw new Error(`Branch ${branch} must have linear history enabled`);
            }

            // Verify force push protection
            if (!protection.data.allow_force_pushes) {
              throw new Error(`Branch ${branch} must have force push protection enabled`);
            }

            // Verify deletion protection
            if (!protection.data.allow_deletions) {
              throw new Error(`Branch ${branch} must have deletion protection enabled`);
            }
